#version: '2'
services:
    conan:
        container_name: conan-server
        build:
            context: .
            dockerfile: Dockerfile
        #image:
        volumes:
          - ./conan:/var/lib/conan
        ports:
          - 9300:9300
        restart: always

    nginx:
      image: nginx:latest
      container_name: webserver
      restart: unless-stopped
      ports:
        - 9999:80
        #- 443:443
      volumes:
        - ./nginx.conf.txt:/etc/nginx/conf.d:ro
        #- /home/ubuntu/ssl:/ssl/
      depends_on:
        - conan